import ChatInput from "@/components/chat/ChatInput";
import ChatList from "@/components/chat/ChatList";
import Head from "next/head";


const Chat = () => {
  return (
    <>
       <Head>
        <title>DEVSTR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/devstr-icon.png" />
      </Head>
      <ChatList />
      <ChatInput />
    </>
  );
};

export default Chat;
