import Head from "next/head";
import Image from "next/image";
import hero from "../pages/devstr.png";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>DEVSTR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/devstr-icon.png" />
      </Head>
      <div className={styles.main}>
        <div className={styles.image}>
          <Image alt="hero" src={hero} />
        </div>
      </div>
    </>
  );
}

// import Image from "next/image"
// import styles from "../styles/Home.module.css"

// export default function Home() {

//  return (
//     <div className={styles.main}>
//         <div className={styles.image}>
//         <Image src={hero}/>
//         </div>
//     </div>
// )
//  }
